# Generated by Django 4.1 on 2022-08-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
