# Generated by Django 4.1 on 2022-08-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_2', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(db_index=True, default=0, max_length=10000),
        ),
    ]
