# Generated by Django 4.1 on 2022-08-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_2', '0005_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
