# Generated by Django 4.1 on 2023-01-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_2', '0006_alter_post_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_pub',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
